export default [
  {
    "employeeId": "EMP-001",
    "fullName": "Agegnew Gebabo",
    "sex": "M",
    "phoneNumber": "0929124099",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Bonga University",
    "employmentDate": "2017-09-22",
    "employmentType": null,
    "salary": 9000,
    "bankAccountNo": 1000013288813,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-002",
    "fullName": "Amanuel Taye",
    "sex": "M",
    "phoneNumber": "0921611353",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Jigjiga MOA",
    "employmentDate": null,
    "employmentType": null,
    "salary": 30000,
    "bankAccountNo": 1000111458239,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-003",
    "fullName": "Amha Taddese",
    "sex": "M",
    "phoneNumber": "0930029062",
    "email": "amha tadesse@efengineering-architect.com",
    "department": "Top Management",
    "designation": "Deputy Manager",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 31000,
    "bankAccountNo": 1000029248919,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-004",
    "fullName": "Ashenafi Mehari",
    "sex": "M",
    "phoneNumber": "0911075892",
    "email": null,
    "department": "Top Management",
    "designation": "Supervision Team Leader",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 30000,
    "bankAccountNo": 1000011731299,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-005",
    "fullName": "Biruk Assefa",
    "sex": "M",
    "phoneNumber": "0923781306",
    "email": "birukassefa@efengineering-architect.com",
    "department": "Design Department",
    "designation": "Architect",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2017-10-17",
    "employmentType": null,
    "salary": 16000,
    "bankAccountNo": 1000533735375,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-006",
    "fullName": "Chaltu Getachew",
    "sex": "F",
    "phoneNumber": "0974407251",
    "email": null,
    "department": "Finance and Administration",
    "designation": "Record Officer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-04-25",
    "employmentType": null,
    "salary": 6000,
    "bankAccountNo": 1000750805144,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-007",
    "fullName": "Debasu Fikadu",
    "sex": "M",
    "phoneNumber": "0913078225",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Borana University",
    "employmentDate": null,
    "employmentType": null,
    "salary": 15000,
    "bankAccountNo": 1000000138014,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-008",
    "fullName": "Eyerus Badeg",
    "sex": "F",
    "phoneNumber": "0923062877",
    "email": null,
    "department": "Office Engineering Department",
    "designation": "Office Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-03-01",
    "employmentType": null,
    "salary": 23000,
    "bankAccountNo": 1000110585423,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-009",
    "fullName": "Elias Mindaye",
    "sex": "M",
    "phoneNumber": "0911765066",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Mattu University",
    "employmentDate": null,
    "employmentType": null,
    "salary": 15000,
    "bankAccountNo": 1000115052587,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-010",
    "fullName": "Endalcachew Seyoum",
    "sex": "M",
    "phoneNumber": "0913051004",
    "email": null,
    "department": "Design Department",
    "designation": "Senior Structural Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-09-15",
    "employmentType": null,
    "salary": 35000,
    "bankAccountNo": 1000071462319,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-011",
    "fullName": "Endale Abdissa",
    "sex": "M",
    "phoneNumber": "0911240283",
    "email": "endale_abdisa@efengineering-architect.com",
    "department": "Top Management",
    "designation": "General Manager",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 60000,
    "bankAccountNo": 1000364539014,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-012",
    "fullName": "Eyosiyas Samuel",
    "sex": "M",
    "phoneNumber": "0973123581",
    "email": null,
    "department": "Contract Administration and Procurement Department",
    "designation": "Office Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-02-22",
    "employmentType": null,
    "salary": 11000,
    "bankAccountNo": 1000560875518,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-013",
    "fullName": "Ifa Dinka",
    "sex": "M",
    "phoneNumber": "0988753358",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Dambidolo University",
    "employmentDate": "2018-05-05",
    "employmentType": null,
    "salary": 25000,
    "bankAccountNo": 1000257518087,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-014",
    "fullName": "Gelana Debela",
    "sex": "M",
    "phoneNumber": "0972497885",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Riverside project (AA)",
    "employmentDate": "2017-09-25",
    "employmentType": null,
    "salary": 20000,
    "bankAccountNo": 1000706678925,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-015",
    "fullName": "Girum Wondwosen",
    "sex": "M",
    "phoneNumber": "0967835378",
    "email": "girumwondosen@efengineering-architect.com",
    "department": "Design Department",
    "designation": "Design Department Head",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 40000,
    "bankAccountNo": 1000318062537,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-016",
    "fullName": "Guluma Jibate",
    "sex": "M",
    "phoneNumber": "0921172396",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Nekemt",
    "employmentDate": "2018-01-01",
    "employmentType": null,
    "salary": 13000,
    "bankAccountNo": 1000218852517,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-017",
    "fullName": "Habte Zena",
    "sex": "M",
    "phoneNumber": "0904112122",
    "email": null,
    "department": "Office Engineering Department",
    "designation": "Office Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-01-13",
    "employmentType": null,
    "salary": 13000,
    "bankAccountNo": 1000301038497,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-018",
    "fullName": "Henok Tesfaye",
    "sex": "M",
    "phoneNumber": "0924075404",
    "email": null,
    "department": "Contract Administration and Procurement Department",
    "designation": "Office Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-04-09",
    "employmentType": null,
    "salary": 10000,
    "bankAccountNo": 1000418883689,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-019",
    "fullName": "Haielegnaw Azene",
    "sex": "M",
    "phoneNumber": "0989112011",
    "email": "hailegnawazene@efengineering-architect.com",
    "department": "Contract Administration and Procurement Department",
    "designation": "Contract Administration Department Head",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 30000,
    "bankAccountNo": 1000205175184,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-020",
    "fullName": "Rebika Shewangzaw",
    "sex": "F",
    "phoneNumber": "0922948618",
    "email": null,
    "department": "Design Department",
    "designation": "Structural Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-08-20",
    "employmentType": null,
    "salary": 20000,
    "bankAccountNo": 1000300002459,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-021",
    "fullName": "Jenberu Abebaw",
    "sex": "M",
    "phoneNumber": "0918134662",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Gewane ATVT",
    "employmentDate": null,
    "employmentType": null,
    "salary": 35000,
    "bankAccountNo": 1000232994812,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-022",
    "fullName": "Kedir Ahmed",
    "sex": "M",
    "phoneNumber": "0710344227",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Mattu University",
    "employmentDate": "2025-07-25",
    "employmentType": null,
    "salary": 10000,
    "bankAccountNo": 1000174616737,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-023",
    "fullName": "Ledate Negese",
    "sex": "M",
    "phoneNumber": "0924414089",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "AACRA Garage",
    "employmentDate": "2017-10-25",
    "employmentType": null,
    "salary": 25000,
    "bankAccountNo": 1000515451707,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-024",
    "fullName": "Lemlem Kiros",
    "sex": "F",
    "phoneNumber": "0911620072",
    "email": "lemlemkiras@efengineering-architect.com",
    "department": "Design Department",
    "designation": "CAD Expert",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 21000,
    "bankAccountNo": 1000198420275,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-025",
    "fullName": "Mesfin Gezahegn",
    "sex": "M",
    "phoneNumber": "0913641245",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Bonga University",
    "employmentDate": null,
    "employmentType": null,
    "salary": 9700,
    "bankAccountNo": 1000130723725,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-026",
    "fullName": "Muluneh Bejiga",
    "sex": "M",
    "phoneNumber": "0921473138",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Bonga University",
    "employmentDate": null,
    "employmentType": null,
    "salary": 7000,
    "bankAccountNo": 1000064265702,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-027",
    "fullName": "Netsanet Dinberu",
    "sex": "F",
    "phoneNumber": "0912142831",
    "email": null,
    "department": "Finance and Administration",
    "designation": "Secretary",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-01-11",
    "employmentType": null,
    "salary": 14000,
    "bankAccountNo": 1000260199076,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-028",
    "fullName": "Serkalem Assefa",
    "sex": "F",
    "phoneNumber": "0987964147",
    "email": "serkalemassefa@efengineering-architect.com",
    "department": "Finance and Administration",
    "designation": "Finance Officer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2017-11-28",
    "employmentType": null,
    "salary": 9000,
    "bankAccountNo": 1000379256876,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-029",
    "fullName": "Soliyana Nekatibeb",
    "sex": "F",
    "phoneNumber": "0913953863",
    "email": "soliyananekatibeb@efengineering-architect.com",
    "department": "Office Engineering Department",
    "designation": "Office Engineering Department Head",
    "assignedWorkLocation": "Head office",
    "employmentDate": null,
    "employmentType": null,
    "salary": 32000,
    "bankAccountNo": 1000073416284,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-030",
    "fullName": "Solomon Girma",
    "sex": "M",
    "phoneNumber": "0911688597",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "MOH Project AA",
    "employmentDate": null,
    "employmentType": null,
    "salary": 20000,
    "bankAccountNo": 1000022167409,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-031",
    "fullName": "Sisay Elias",
    "sex": "M",
    "phoneNumber": "0912116140",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Borana University",
    "employmentDate": "2018-11-22",
    "employmentType": null,
    "salary": 18000,
    "bankAccountNo": 1000550590089,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-032",
    "fullName": "Surafel Nigussie",
    "sex": "M",
    "phoneNumber": "0985365154",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "Dambidolo University",
    "employmentDate": "2017-12-29",
    "employmentType": null,
    "salary": 35000,
    "bankAccountNo": 1000332705664,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-033",
    "fullName": "Tadele Assefa",
    "sex": "M",
    "phoneNumber": "0973613894",
    "email": "tadelleassefa@efengineering-architect.com",
    "department": "Design Department",
    "designation": "Electrical Engineer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-11-21",
    "employmentType": null,
    "salary": 18000,
    "bankAccountNo": 1000469351665,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-034",
    "fullName": "Tariku Negesa",
    "sex": "M",
    "phoneNumber": "0919421910",
    "email": null,
    "department": "Finance and Administration",
    "designation": "IT Officer",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2018-10-22",
    "employmentType": null,
    "salary": 13000,
    "bankAccountNo": 1000111606629,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-035",
    "fullName": "Yasin Kedir",
    "sex": "M",
    "phoneNumber": "0906621435",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Resident Engineer",
    "assignedWorkLocation": "OIP (RTC's)",
    "employmentDate": "2018-01-09",
    "employmentType": null,
    "salary": 30000,
    "bankAccountNo": 1000111284125,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-036",
    "fullName": "Yared Arega",
    "sex": "M",
    "phoneNumber": "0968153070",
    "email": null,
    "department": "Supervision and Project Follow-up Department",
    "designation": "Assistant Resident Engineer",
    "assignedWorkLocation": "Borana University",
    "employmentDate": null,
    "employmentType": null,
    "salary": 12000,
    "bankAccountNo": 1000091071162,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-037",
    "fullName": "Zemzem Kebede",
    "sex": "F",
    "phoneNumber": "0934206276",
    "email": null,
    "department": "Finance and Administration",
    "designation": "Janitor",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2016-01-21",
    "employmentType": null,
    "salary": 5500,
    "bankAccountNo": 1000352482831,
    "otherRelevantInformation": null
  },
  {
    "employeeId": "EMP-038",
    "fullName": "Zenash Desta",
    "sex": "F",
    "phoneNumber": "0972976891",
    "email": null,
    "department": "Finance and Administration",
    "designation": "Janitor",
    "assignedWorkLocation": "Head office",
    "employmentDate": "2017-11-25",
    "employmentType": null,
    "salary": 5500,
    "bankAccountNo": 1000710919317,
    "otherRelevantInformation": null
  }
];
